src/cafe_order_management/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('orders.urls', 'orders')),
]

src/orders/urls.py
from django.urls import path
from . import views
from .views import OrderListAPIView, OrderDetailAPIView

app_name = 'orders'

urlpatterns = [
    path('', views.order_list, name='order_list'),
    path('add_order/', views.add_order, name='add_order'),
    path('delete_order/', views.delete_order, name='delete_order'),
    path('search_order/', views.search_order, name='search_order'),
    path('change_status', views.change_status, name='change_status'),
    path('revenue_report/', views.revenue_report, name='revenue_report'),
    path('api/orders/', OrderListAPIView.as_view(), name='order-list-api'),
    path('api/orders/<int:pk>/', OrderDetailAPIView.as_view(), name='order-detail-api'),
]

src/templates/base.html
{% url 'orders:add_order' as add_order_url %}
{% url 'orders:delete_order' as delete_order_url %}
{% url 'orders:search_order' as search_order_url %}
{% url 'orders:change_status' as change_status_url %}
{% url 'orders:revenue_report' as revenue_url %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <title>{% block title %}Base title{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light container" style="background-color: #e3f2fd;">
      <a class="navbar-brand" href="{% url 'orders:order_list' %}">Список заказов</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item {% if request.path == add_order_url %} active {% endif %}">
            <a class="nav-link" href="{% url 'orders:add_order' %}">Добавить заказ </a>
          </li>
          <li class="nav-item {% if request.path == delete_order_url %} active {% endif %}">
            <a class="nav-link" href="{% url 'orders:delete_order' %}">Удалить заказ</a>
          </li>
          <li class="nav-item {% if request.path == search_order_url %} active {% endif %}">
            <a class="nav-link" href="{% url 'orders:search_order' %}">Найти заказ</a>
          </li>
            <li class="nav-item {% if request.path == change_status_url %} active {% endif %}">
            <a class="nav-link" href="{% url 'orders:change_status' %}">Изменить статус заказа</a>
          </li>
            <li class="nav-item {% if request.path == revenue_url %} active {% endif %}">
            <a class="nav-link" href="{% url 'orders:revenue_report' %}">Выручка</a>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container">
      <div class="row">
        <div class="col-md-8 mx-auto my-2">
          {% if messages %}
            {% for message in messages %}
              {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important:
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                  {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                </div>
              {% else %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                  {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                </div>
              {% endif %}
            {% endfor %}
          {% endif %}
        </div>
      </div>
    </div>
    <div class="container">
      {% block content %}{% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script>
      $(document).ready(function() {
        $('.js-example-basic-single').select2();
        $('.js-example-basic-multiple').select2();
      });
    </script>
  </body>
</html>